In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)

df2=dataset1

df = pd.get_dummies(df2, drop_first=True)

X=df.drop('classification_yes',axis=1)
Y=df['classification_yes']

In [3]:
df

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...      False        False       False   
1    137.528754  4.627244  10.700000  ...       True        False       False   
2    138.000000  4.400000  12.000000  ...       True        False       False   
3    138.000000  3.200000   8.100000  ...       True        False       False   
4    137.528754  4.627244  11.800000  ...       True        False       False   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...       True        False       False   
395  137.528754  4.627244   8.700000  ...       True        False       False   
396  134.000000  2.700000   9.100000  ...       True        False       False   
397  142.000000  5.500000   8.500000  ...       True        False       False   
398  140.000000  5.000000  16.300000  ...       True        False       False   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0      False   False    False       True    True    False                True  
1      False   False    False       True   False    False                True  
2      False   False    False       True   False    False                True  
3      False   False    False       True   False     True                True  
4      False   False    False       True   False    False                True  
..       ...     ...      ...        ...     ...      ...                 ...  
394    False   False    False       True   False    False                True  
395     True    True    False       True   False     True                True  
396     True    True    False      False   False    False                True  
397     True    True    False       True   False     True                True  
398    False   False    False       True   False    False               False  

[399 rows x 28 columns]

In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

In [5]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [6]:
X_train

array([[ 1.08359152,  1.71995901,  2.49783085, ...,  0.50587104,
        -0.51562876, -0.43623217],
       [-1.12237006,  0.98402682,  0.91842938, ...,  0.50587104,
        -0.51562876, -0.43623217],
       [-1.18364677,  0.24809463, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217],
       ...,
       [-0.44832624,  0.24809463, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217],
       [-1.3674769 ,  0.24809463, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217],
       [-0.08066598, -1.22376976, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217]])

In [7]:
X_test

array([[-0.38704953, -0.48783757, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217],
       [ 0.83848468,  0.98402682,  0.91842938, ..., -1.97678838,
        -0.51562876, -0.43623217],
       [ 1.02231481, -0.48783757, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217],
       ...,
       [ 0.77720797, -1.22376976,  0.91842938, ..., -1.97678838,
        -0.51562876, -0.43623217],
       [ 1.26742165, -0.48783757, -0.66097209, ...,  0.50587104,
         1.93937981, -0.43623217],
       [ 0.9610381 , -1.22376976, -0.66097209, ...,  0.50587104,
        -0.51562876, -0.43623217]])

In [8]:
# Applying LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda = LDA(n_components = 1)
X_train1 = lda.fit_transform(X_train,y_train)
X_test1 = lda.transform(X_test)

explained_variance = lda.explained_variance_ratio_
feature_names=lda.get_feature_names_out(input_features=None)

print("lda:",lda)
print("explained_variance:",explained_variance)
print("feature_names:",feature_names)

lda: LinearDiscriminantAnalysis(n_components=1)
explained_variance: [1.]
feature_names: ['lineardiscriminantanalysis0']


In [9]:
X_train1

array([[-1.19295746],
       [-0.9727614 ],
       [ 3.53581083],
       [ 3.63653091],
       [-2.32171708],
       [-1.87286893],
       [ 1.94035944],
       [ 0.18843777],
       [ 0.56767341],
       [-3.95288532],
       [-1.38869563],
       [-1.04749716],
       [ 1.92005085],
       [ 0.71359632],
       [-2.23100308],
       [-1.09516459],
       [-2.2295652 ],
       [ 0.19477264],
       [-0.25168344],
       [-0.3117815 ],
       [-0.45070106],
       [ 0.87208099],
       [ 2.17082786],
       [-2.63009251],
       [ 2.35424767],
       [-2.20507531],
       [ 1.6541583 ],
       [-1.90843509],
       [ 1.86481808],
       [-2.94165004],
       [-1.70819581],
       [ 1.99105078],
       [ 0.14866287],
       [ 2.63572395],
       [-1.99577494],
       [-2.36546185],
       [-0.02193525],
       [ 2.41474247],
       [ 2.15192524],
       [ 2.27072556],
       [-0.75297794],
       [ 1.9921241 ],
       [-3.53633098],
       [-0.98299517],
       [-0.53890428],
       [ 2

In [10]:
X_test1

array([[ 3.54420132e+00],
       [-4.55010779e-01],
       [ 2.26584201e+00],
       [-2.76595747e+00],
       [-1.87715751e+00],
       [-1.45200644e+00],
       [-3.63962319e+00],
       [-1.19878905e+00],
       [ 1.64608368e+00],
       [ 2.68143284e+00],
       [ 2.28425273e-01],
       [ 4.48146142e-01],
       [ 2.18209825e+00],
       [-1.26877344e+00],
       [ 2.12944976e+00],
       [ 2.37045521e+00],
       [-8.63262703e-01],
       [ 2.54067950e+00],
       [-2.79482107e+00],
       [-1.93478672e+00],
       [ 2.13989983e+00],
       [-1.47317008e+00],
       [-1.57242186e+00],
       [ 1.85880283e+00],
       [-7.24495508e+00],
       [ 1.93377799e+00],
       [ 3.26805984e+00],
       [ 3.21241482e+00],
       [-1.31908598e+00],
       [ 2.14664267e-01],
       [-3.52282047e-01],
       [-2.65293405e+00],
       [ 1.48890850e+00],
       [ 1.75317604e+00],
       [ 2.42725601e+00],
       [ 3.09569804e+00],
       [ 9.95346296e-01],
       [ 2.10106661e+00],
       [-1.9

In [11]:
explained_variance

array([1.])

In [12]:
# Fitting Logistic Regression to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train1, y_train)

LogisticRegression(random_state=0)

In [13]:
# Predicting the Test set results
y_pred = classifier.predict(X_test1)

In [14]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[32,  0],
       [ 2, 46]], dtype=int64)

In [15]:
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 
        
Accuracy=accuracy_score(y_test, y_pred)
report=classification_report(y_test, y_pred)
Accuracy

0.975