In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import numpy as np
from sklearn.preprocessing import StandardScaler

In [2]:
dataset1=pd.read_csv("prep.csv",index_col=None)

df2=dataset1

df = pd.get_dummies(df2,dtype= int, drop_first=True)

indep_X=df.drop('classification_yes',axis=1)

dep_Y=df['classification_yes']

df

age         bp   al   su         bgr          bu        sc  \
0     2.000000  76.459948  3.0  0.0  148.112676   57.482105  3.077356   
1     3.000000  76.459948  2.0  0.0  148.112676   22.000000  0.700000   
2     4.000000  76.459948  1.0  0.0   99.000000   23.000000  0.600000   
3     5.000000  76.459948  1.0  0.0  148.112676   16.000000  0.700000   
4     5.000000  50.000000  0.0  0.0  148.112676   25.000000  0.600000   
..         ...        ...  ...  ...         ...         ...       ...   
394  51.492308  70.000000  0.0  0.0  219.000000   36.000000  1.300000   
395  51.492308  70.000000  0.0  2.0  220.000000   68.000000  2.800000   
396  51.492308  70.000000  3.0  0.0  110.000000  115.000000  6.000000   
397  51.492308  90.000000  0.0  0.0  207.000000   80.000000  6.800000   
398  51.492308  80.000000  0.0  0.0  100.000000   49.000000  1.000000   

            sod       pot       hrmo  ...  pc_normal  pcc_present  ba_present  \
0    137.528754  4.627244  12.518156  ...          0            0           0   
1    137.528754  4.627244  10.700000  ...          1            0           0   
2    138.000000  4.400000  12.000000  ...          1            0           0   
3    138.000000  3.200000   8.100000  ...          1            0           0   
4    137.528754  4.627244  11.800000  ...          1            0           0   
..          ...       ...        ...  ...        ...          ...         ...   
394  139.000000  3.700000  12.500000  ...          1            0           0   
395  137.528754  4.627244   8.700000  ...          1            0           0   
396  134.000000  2.700000   9.100000  ...          1            0           0   
397  142.000000  5.500000   8.500000  ...          1            0           0   
398  140.000000  5.000000  16.300000  ...          1            0           0   

     htn_yes  dm_yes  cad_yes  appet_yes  pe_yes  ane_yes  classification_yes  
0          0       0        0          1       1        0                   1  
1          0       0        0          1       0        0                   1  
2          0       0        0          1       0        0                   1  
3          0       0        0          1       0        1                   1  
4          0       0        0          1       0        0                   1  
..       ...     ...      ...        ...     ...      ...                 ...  
394        0       0        0          1       0        0                   1  
395        1       1        0          1       0        1                   1  
396        1       1        0          0       0        0                   1  
397        1       1        0          1       0        1                   1  
398        0       0        0          1       0        0                   0  

[399 rows x 28 columns]

In [3]:
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test

def PCA(X_train, X_test,n):
        from sklearn.decomposition import PCA
        pca = PCA(n_components = n)
        X_train1 = pca.fit_transform(X_train)
        print("X_train",X_train.shape)
        print("X_train1",X_train1.shape)
        print(X_train1)
        X_test1 = pca.transform(X_test)
        print("X_test",X_test.shape)
        print("X_test1",X_test1.shape)
        print(X_test1)
        explained_variance = pca.explained_variance_ratio_
        print("pca:",pca)
        print("explained_variance:",explained_variance)
        # Get the components
        components = pca.components_
        print("components")
        print(components)
        # Create a DataFrame with components and features
        component_df = pd.DataFrame(components, columns=indep_X.columns)
        print("compentent_df")
        print(component_df)
        # Find the most important features in the first principal component
        top_features_pc1 = component_df.loc[0].abs().sort_values(ascending=False)
        print("top_features_pc1")
        print(top_features_pc1)
        top_features_pc2 = component_df.loc[1].abs().sort_values(ascending=False)
        print("top_features_pc2")
        print(top_features_pc2)
        top_features_pc3 = component_df.loc[2].abs().sort_values(ascending=False)
        print("top_features_pc3")
        print(top_features_pc3)
        top_features_pc4 = component_df.loc[3].abs().sort_values(ascending=False)
        print("top_features_pc4")
        print(top_features_pc4)
        top_features_pc5 = component_df.loc[4].abs().sort_values(ascending=False)
        print("top_features_pc5")
        print(top_features_pc5)
        # Get the important feature names based on their contribution
        # idxmax() returns the index of the highest absolute value in each row
        important_features = component_df.apply(lambda x: x.abs().idxmax(), axis=1)
        # Output the most important features for each component
        print("Most important features for each PCA component:")
        print(important_features)
        return X_train1,X_test1
    
def cm_prediction(classifier,X_test1):
        y_pred = classifier.predict(X_test1)
        
        # Making the Confusion Matrix
        from sklearn.metrics import confusion_matrix
        cm = confusion_matrix(y_test, y_pred)
        
        from sklearn.metrics import accuracy_score 
        from sklearn.metrics import classification_report 
        
        Accuracy=accuracy_score(y_test, y_pred)
        report=classification_report(y_test, y_pred)
        
        return  classifier,Accuracy,report,X_test1,y_test,cm

def logistic(X_train1,y_train,X_test1):
        from sklearn.linear_model import LogisticRegression
        classifier = LogisticRegression(random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm      
    
def svm_linear(X_train1,y_train,X_test1):              
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'linear', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def svm_NL(X_train1,y_train,X_test1):             
        from sklearn.svm import SVC
        classifier = SVC(kernel = 'rbf', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm

def Navie(X_train1,y_train,X_test1):       
        from sklearn.naive_bayes import GaussianNB
        classifier = GaussianNB()
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm         
    
def knn(X_train1,y_train,X_test1):
        from sklearn.neighbors import KNeighborsClassifier
        classifier = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def Decision(X_train1,y_train,X_test1):
        from sklearn.tree import DecisionTreeClassifier
        classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm      


def random(X_train1,y_train,X_test1):
        from sklearn.ensemble import RandomForestClassifier
        classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
        classifier.fit(X_train1, y_train)
        classifier,Accuracy,report,X_test1,y_test,cm=cm_prediction(classifier,X_test1)
        return  classifier,Accuracy,report,X_test1,y_test,cm
    
def selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['PCA'],columns=['Logistic','SVMl','SVMnl','KNN','Navie','Decision','Random'])
    for number,idex in enumerate(dataframe.index):      
        dataframe['Logistic'][idex]=acclog[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['KNN'][idex]=accknn[number]
        dataframe['Navie'][idex]=accnav[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [4]:
X_train, X_test, y_train, y_test = split_scalar(indep_X,dep_Y)

In [5]:
PCA = PCA(X_train, X_test,5)

acclog=[]
accsvml=[]
accsvmnl=[]
accknn=[]
accnav=[]
accdes=[]
accrf=[]

#n_components = 5
#selected_features = indep_X.columns[:n_components]
#selected_features

X_train (299, 27)
X_train1 (299, 5)
[[-0.25128676  0.37856611 -1.04857645  0.49305423 -0.73411699]
 [-1.33765785  0.50472567  0.76069328 -0.41795485 -0.50012094]
 [-2.57133641  0.22793673 -0.16633715  0.06674013  0.83886036]
 ...
 [-0.44615013 -0.46194954  1.40340525 -0.77930438 -0.16864546]
 [-2.70323719  0.01339849  0.23856626  0.35622769 -0.2581307 ]
 [-2.70561725 -0.13090682 -0.12676888  0.42533048 -0.0144668 ]]
X_test (100, 27)
X_test1 (100, 5)
[[-3.43850809e+00  1.05728920e-01  3.92571499e-01  4.80198055e-01
   4.86657270e-01]
 [ 8.90152029e-01 -7.93922709e-01  1.56321622e+00 -4.65655172e-01
   7.52326225e-01]
 [-2.58112498e+00 -1.52239499e-01 -3.20521000e-01  5.76477881e-02
   9.59960776e-02]
 [ 2.05328575e+00 -2.00940148e+00 -2.64930607e+00 -1.24477369e+00
   8.50615388e-01]
 [ 7.07553627e-01 -4.41221360e-01  2.51205502e-01  8.32759486e-01
  -3.34924544e-01]
 [ 1.01058442e+00 -1.56123328e+00  3.30008056e+00 -1.82135896e-01
   1.28724036e+00]
 [ 5.95275491e+00  1.23619484e+00  1

In [6]:
PCA

(array([[-0.25128676,  0.37856611, -1.04857645,  0.49305423, -0.73411699],
        [-1.33765785,  0.50472567,  0.76069328, -0.41795485, -0.50012094],
        [-2.57133641,  0.22793673, -0.16633715,  0.06674013,  0.83886036],
        ...,
        [-0.44615013, -0.46194954,  1.40340525, -0.77930438, -0.16864546],
        [-2.70323719,  0.01339849,  0.23856626,  0.35622769, -0.2581307 ],
        [-2.70561725, -0.13090682, -0.12676888,  0.42533048, -0.0144668 ]]),
 array([[-3.43850809e+00,  1.05728920e-01,  3.92571499e-01,
          4.80198055e-01,  4.86657270e-01],
        [ 8.90152029e-01, -7.93922709e-01,  1.56321622e+00,
         -4.65655172e-01,  7.52326225e-01],
        [-2.58112498e+00, -1.52239499e-01, -3.20521000e-01,
          5.76477881e-02,  9.59960776e-02],
        [ 2.05328575e+00, -2.00940148e+00, -2.64930607e+00,
         -1.24477369e+00,  8.50615388e-01],
        [ 7.07553627e-01, -4.41221360e-01,  2.51205502e-01,
          8.32759486e-01, -3.34924544e-01],
        [ 1.010

In [7]:
X_train1,X_test1=PCA

In [8]:
X_train1.shape

(299, 5)

In [9]:
classifier,Accuracy,report,X_test,y_test,cm=logistic(X_train1,y_train,X_test1)
acclog.append(Accuracy)

classifier,Accuracy,report,X_test,y_test,cm=svm_linear(X_train1,y_train,X_test1)  
accsvml.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=svm_NL(X_train1,y_train,X_test1)  
accsvmnl.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=knn(X_train1,y_train,X_test1)  
accknn.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Navie(X_train1,y_train,X_test1)  
accnav.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=Decision(X_train1,y_train,X_test1)  
accdes.append(Accuracy)
    
classifier,Accuracy,report,X_test,y_test,cm=random(X_train1,y_train,X_test1)  
accrf.append(Accuracy)
    
result=selectk_Classification(acclog,accsvml,accsvmnl,accknn,accnav,accdes,accrf)

In [10]:
result
#5

Logistic  SVMl SVMnl   KNN Navie Decision Random
PCA     0.99  0.99   1.0  0.99   1.0     0.99    1.0